array = []
array.append(0)
array.append(1)
array.append(2)
array.append(3)
array.append(4)
array.append(5)
array.append(6)
array.insert(3, 69)
print(array)
length = len(array)
array.pop(3)
array.pop(0)
array.pop()
print(array)